version: '3'
services:
 mongo:
  image: mongo:latest
  container_name: mymongo
  ports:
   - 27017
  volumes:
   - ./data/db:/data/db
   - /etc/timezone:/etc/timezone
   - /etc/localtime:/etc/localtime
  deploy:
   restart_policy:
    condition : on-failure
 hotel:
  build:
   context : ./
   dockerfile: Dockerfile
  container_name: myhotel
  depends_on:
   - mongo
  ports: 
   - 8080:8080
   - 27017
  volumes:
   - /etc/timezone:/etc/timezone
   - /etc/localtime:/etc/localtime  deploy:
   restart_policy:
    condition : on-failure