version: '3'
services:
 mongo:
  image: mongo:latest
  container_name: mymongo
  ports:
   - 27017
#  command: chown -R mongodb /data/db/
  volumes:
   - ./data/db:/data/db
  deploy:
   restart_policy:
    condition : on-failure
 hotel:
  build:
   context : ./
   dockerfile: Dockerfile
  container_name: myhotel
  depends_on:
   - mongo
  ports: 
   - 8080:8080
   - 27017
   - 4444
  deploy:
   restart_policy:
    condition : on-failure