version: '3'
services:
 mongo:
  image: mongo:latest
  container_name: mymongo
  ports:
   - 27017
#  command: chown -R mongodb /data/db/
  volumes:
   - ./data/db:/data/db
  deploy:
   restart_policy:
    condition : on-failure
 selenium-hub:
  image: selenium/hub:3.141.59-bismuth
  container_name: selenium-hub
  ports:
   - "4444:4444"
 chrome:
  image: selenium/node-chrome:3.141.59-bismuth
  depends_on:
   - selenium-hub
  environment:
   - HUB_HOST=selenium-hub
   - HUB_PORT=4444
 hotel:
  build:
   context : ./
   dockerfile: Dockerfile
  container_name: myhotel
  depends_on:
   - mongo
   - chrome
  ports: 
   - 8080:8080
   - 27017
   - 4444
  deploy:
   restart_policy:
    condition : on-failure